---
name: <%= Dir.pwd.split('/')[-1] %>
root: <%= Dir.pwd %>

pre_window:
  - source .venv/bin/activate

on_project_exit:
  - echo "bye"

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - nodemon -w src --exec "rye run flask --debug --app=src.app run" || true

        - npx just tailwind
        -
