---
name: <%= Dir.pwd.split('/')[-1] %>
root: <%= Dir.pwd %>

pre_window:
  - source .venv/bin/activate

on_project_exit:
  - echo "bye"

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - rye run flask --app=src.app run
        - npx just tailwind
        -
