---
name: <%= Dir.pwd.split('/')[-1] %>
root: <%= Dir.pwd %>

on_project_exit:
  - echo "bye"

windows:
  - editor:
      layout: main-vertical
      panes:
        - poetry run nvim
        - poetry run flask --app=src.app run
        - npx just tailwind
        -
